/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionId = IDL.Nat;
export const ClassStatus = IDL.Variant({
  'canceled' : IDL.Null,
  'pendingPayment' : IDL.Record({
    'sessionId' : SessionId,
    'amount' : IDL.Nat,
  }),
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : ClassStatus,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'sessionId' : SessionId,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ClassId = IDL.Nat;
export const DanceClass = IDL.Record({
  'id' : ClassId,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'instructor' : IDL.Text,
  'description' : IDL.Text,
  'level' : IDL.Text,
  'style' : IDL.Text,
  'price' : IDL.Nat,
});
export const Session = IDL.Record({
  'id' : SessionId,
  'startTime' : Time,
  'duration' : IDL.Nat,
  'instructor' : IDL.Text,
  'classId' : ClassId,
  'onlineLink' : IDL.Text,
  'capacity' : IDL.Nat,
  'location' : IDL.Text,
});
export const ContactInquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const VideoId = IDL.Nat;
export const VideoLesson = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'instructor' : IDL.Text,
  'style' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookSession' : IDL.Func([SessionId], [Booking], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDanceClass' : IDL.Func([DanceClass], [], []),
  'createSession' : IDL.Func([Session], [], []),
  'getAllContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getAllDanceClasses' : IDL.Func([], [IDL.Vec(DanceClass)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllVideoLessons' : IDL.Func([], [IDL.Vec(VideoLesson)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDanceClass' : IDL.Func([ClassId], [IDL.Opt(DanceClass)], ['query']),
  'getSession' : IDL.Func([SessionId], [IDL.Opt(Session)], ['query']),
  'getSessionsForClass' : IDL.Func([ClassId], [IDL.Vec(Session)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitContactInquiry' : IDL.Func([ContactInquiry], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'uploadVideoLesson' : IDL.Func([VideoLesson], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionId = IDL.Nat;
  const ClassStatus = IDL.Variant({
    'canceled' : IDL.Null,
    'pendingPayment' : IDL.Record({
      'sessionId' : SessionId,
      'amount' : IDL.Nat,
    }),
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : ClassStatus,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'sessionId' : SessionId,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ClassId = IDL.Nat;
  const DanceClass = IDL.Record({
    'id' : ClassId,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'instructor' : IDL.Text,
    'description' : IDL.Text,
    'level' : IDL.Text,
    'style' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Session = IDL.Record({
    'id' : SessionId,
    'startTime' : Time,
    'duration' : IDL.Nat,
    'instructor' : IDL.Text,
    'classId' : ClassId,
    'onlineLink' : IDL.Text,
    'capacity' : IDL.Nat,
    'location' : IDL.Text,
  });
  const ContactInquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const VideoId = IDL.Nat;
  const VideoLesson = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'instructor' : IDL.Text,
    'style' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookSession' : IDL.Func([SessionId], [Booking], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDanceClass' : IDL.Func([DanceClass], [], []),
    'createSession' : IDL.Func([Session], [], []),
    'getAllContactInquiries' : IDL.Func(
        [],
        [IDL.Vec(ContactInquiry)],
        ['query'],
      ),
    'getAllDanceClasses' : IDL.Func([], [IDL.Vec(DanceClass)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllVideoLessons' : IDL.Func([], [IDL.Vec(VideoLesson)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDanceClass' : IDL.Func([ClassId], [IDL.Opt(DanceClass)], ['query']),
    'getSession' : IDL.Func([SessionId], [IDL.Opt(Session)], ['query']),
    'getSessionsForClass' : IDL.Func([ClassId], [IDL.Vec(Session)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitContactInquiry' : IDL.Func([ContactInquiry], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'uploadVideoLesson' : IDL.Func([VideoLesson], [], []),
  });
};

export const init = ({ IDL }) => { return []; };