/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : ClassStatus,
  'user' : Principal,
  'timestamp' : Time,
  'sessionId' : SessionId,
}
export type ClassId = bigint;
export type ClassStatus = { 'canceled' : null } |
  { 'pendingPayment' : { 'sessionId' : SessionId, 'amount' : bigint } } |
  { 'confirmed' : null };
export interface ContactInquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface ContactInquiryInput {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface DanceClass {
  'id' : ClassId,
  'title' : string,
  'duration' : bigint,
  'instructor' : string,
  'description' : string,
  'level' : string,
  'style' : string,
  'price' : bigint,
}
export interface Session {
  'id' : SessionId,
  'startTime' : Time,
  'duration' : bigint,
  'instructor' : string,
  'classId' : ClassId,
  'style' : string,
  'onlineLink' : string,
  'capacity' : bigint,
  'location' : string,
}
export type SessionId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface StyleSessionCount { 'count' : bigint, 'style' : string }
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VideoId = bigint;
export interface VideoLesson {
  'id' : VideoId,
  'title' : string,
  'duration' : bigint,
  'instructor' : string,
  'style' : string,
  'videoUrl' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookSession' : ActorMethod<[SessionId], Booking>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDanceClass' : ActorMethod<[DanceClass], undefined>,
  'createSession' : ActorMethod<[Session], undefined>,
  'ensureMinimumMonthlySessions' : ActorMethod<
    [Array<string>],
    Array<StyleSessionCount>
  >,
  'getAllContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getAllDanceClasses' : ActorMethod<[], Array<DanceClass>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllVideoLessons' : ActorMethod<[], Array<VideoLesson>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDanceClass' : ActorMethod<[ClassId], [] | [DanceClass]>,
  'getGlobalSessionSchedule' : ActorMethod<[], Array<Session>>,
  'getSession' : ActorMethod<[SessionId], [] | [Session]>,
  'getSessionsForClass' : ActorMethod<[ClassId], Array<Session>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitContactInquiry' : ActorMethod<[ContactInquiryInput], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'uploadVideoLesson' : ActorMethod<[VideoLesson], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];